<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.18" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Context\" />
    <Folder Include="Configurations\" />
    <Folder Include="Migrations\" />
    <Folder Include="Seed\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrbitERP.Domain\OrbitERP.Domain.csproj" />
    <ProjectReference Include="..\OrbitERP.Shared\OrbitERP.Shared.csproj" />
    <ProjectReference Include="..\OrbitERP.Application\OrbitERP.Application.csproj" />
  </ItemGroup>

</Project>
