namespace OrbitERP.Domain.Common;

/// <summary>
/// Unified base class for every OrbitERP domain entity.
/// <para>
/// Every entity carries the full audit trail: identity, creation timestamp,
/// last-modification timestamp, and the IDs of the users who created and last
/// modified the record.  Chandar has confirmed that the SQL schema will be
/// updated so that all tables contain these five columns.
/// </para>
/// <para>
/// <b>Primary Key strategy:</b> IDs are <see cref="Guid"/> values generated
/// server-side with <c>NEWSEQUENTIALID()</c>. Fluent API configurations declare
/// <c>HasDefaultValueSql("NEWSEQUENTIALID()")</c> on every entity so that
/// EF Core never substitutes a client-generated <see cref="Guid.NewGuid()"/>
/// value, which would break the sequential ordering that clustered index
/// performance depends upon.
/// </para>
/// </summary>
public abstract class BaseEntity : IAuditableEntity
{
    /// <summary>
    /// Primary key. Generated by SQL Server using <c>NEWSEQUENTIALID()</c>.
    /// Do not assign this value manually; let the database generate it.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// UTC timestamp at which the record was first inserted.
    /// Set automatically in <c>ApplicationDbContext.SaveChangesAsync</c>
    /// and backed by <c>DEFAULT GETUTCDATE()</c> in SQL.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// UTC timestamp of the most recent update to this record.
    /// <c>null</c> when the record has never been modified after creation.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// <see cref="Domain.Entities.Administration.User.Id"/> of the user who
    /// created this record.  <c>null</c> for system-generated records (e.g.
    /// seed data, background jobs).
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// <see cref="Domain.Entities.Administration.User.Id"/> of the user who
    /// last modified this record.  <c>null</c> when <see cref="UpdatedAt"/>
    /// is also <c>null</c>.
    /// </summary>
    public Guid? UpdatedBy { get; set; }
}